Function.extend
Function.implement
Function._
Function.empty
Function.identity
Function.context
Function.lambda
Function.pluck
Function.invoke
Function.sequence
Function.concatenate
Function.concat
Function.compose
Function.overload
Function.and
Function.or
Function.xor
Function.TRACE_NONE
Function.TRACE_ALL
Function.TRACE_ARGUMENTS
Function.TRACE_CONTEXT
Function.TRACE_RETURN
Function.TRACE_TIME
Function.TRACE_STACK
Function.prototype.overloadSetter
Function.prototype.overloadGetter
Function.prototype.toFunction
Function.prototype.bind
Function.prototype.wrap
Function.prototype.getOrigin
Function.prototype.memoize
Function.prototype.memoize.call(function(){},{args:0,context:null,returnValue:0})
Function.prototype.traced
Function.prototype.partial
Function.prototype.curry
Function.prototype.rcurry
Function.prototype.not
Function.prototype.append
Function.prototype.prepend
Function.prototype.overload
Function.prototype.saturate
Function.prototype.aritize
Function.prototype.getArgs
Function.prototype.getArity
Function.prototype.foreach
Function.prototype.each
Function.prototype.every
Function.prototype.some
Function.prototype.filter
Function.prototype.map
Function.prototype.reduce
Function.prototype.reduceRight
Function.prototype.sort
Function.prototype.foldl
Function.prototype.foldr
Array.prototype.toFunction
Hash.prototype.toFunction
Object.toFunction
_
console
console.log
console.error
console.group
console.groupEnd
console.time
console.timeEnd
console.trace
Function.prototype._origin
