name: FunctionTools
author: michael
category: Native
tags: [
    FunctionTools, function, functional, functional programming,
    # Function::_
    underscore, _,
    # Function::empty
    empty,
    # Function::identity
    identity,
    # Function::lambda
    lambda,
    # Function::combine, Function::compose
    combine, compose, concat, concatenate,
    # Function:: overload
    overload,
    # wrap()
    wrap, wrapping, wrapper
    # memoize()
    memo, memoize, memoization, cache, caching,
    # partial()
    partial, default, arguments,
    # curry()
    curry, default arguments,
    # not()
    not,
    # prepend()
    prepend,
    # append()
    append,
    # getArgs()
    getArgs, get arguments, arglist, argument, list, argument list,
    # Array.toFunction, Hash.toFunction
    toFunction, Array.toFunction, Hash.toFunction
]
current: 0.1
docs: 'http://github.com/michaelficarra/FunctionTools/blob/master/README.md'
#demo: ''
